keys:
  - &server_saitama age13y59mzrlrlckjls3j3w4avxyrtre6jcnehnszpv2aummj8a0sc0sl43652
  - &server_kazuma age1c6h8l08uyktp45eartmdyy0p0x0w3pnet5dcvy4lg00guxmrq4xqdpcdfe
  - &admin_tie age1y20x3mwhjaax0q5zc9mwytuste6r02m2m2ee26sz4595u0yxtp3qpk9z4t
creation_rules:
  - path_regex: ^hosts/saitama/secrets\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_saitama
  - path_regex: ^hosts/kazuma/secrets\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_kazuma
