name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Set up cachix
        uses: cachix/cachix-action@v10
        with:
          name: yamporg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deploy-rs
        run: nix develop "${installable}" -c deploy "${installable}"
        env:
          installable: github:${{ github.repository }}/${{ github.sha }}
          NIX_CONFIG: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
