name: Deploy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - server: nixos@kazuma.tie.rip
            system: kazuma
    name: Deploy ${{ matrix.system }}
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: yamporg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Switch configuration
        run: nix run nixpkgs#nixos-rebuild -- switch --target-host "$target" --flake "$installable"
        env:
          NIX_SSHOPTS: "-o CheckHostIP=no -o UserKnownHostsFile=ssh/known_hosts.txt"
          installable: "github:${{ github.repository }}/${{ github.sha }}#${{ matrix.system }}"
          target: ${{ matrix.server }}
